version: "3.7"

services:
  snippet-manager:
    container_name: snippet-manager-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    environment:
      DB_URL: jdbc:postgresql://snippet-manager-db:5432/snippet-manager
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

  api:
    container_name: "asset_service"
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "8081:8080"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_APP_NAME: "asset service"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace

  snippet-manager-db:
    container_name: snippet-manager-db
    image: postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=snippet-manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  blob:
    external: false
  postgres-data: