name: "Continuous Deployment"
on:
  push:
    branches:
      - dev
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Create Short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.SNIPPET_MANAGER_TOKEN }}

      - name: Push to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/ingsis-group-9/snippet-manager:${{ steps.short-sha.outputs.sha }}
            ghcr.io/ingsis-group-9/snippet-manager:latest

      - name: Update Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST_DEV }}
          username: "azureuser"
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/projects/infra
            docker-compose stop snippet-manager
            docker-compose pull snippet-manager
            docker-compose up snippet-manager -d --build
